### ISSUE TITLE
W/beacon: onUserAction return false, because eventName:[MTT_CORE_DNS_RESOLVE_INFO] is not allowed in server strategy!

### ISSUE THREAD

**Issue by Mojo-Lee** [Im-Kevin/cordova.plugins.X5WebView#1]
你好，64位手机可以运行我的H5 app，但是app里通过websocket请求的操作就没有反应，报这个错：
W/beacon: onUserAction return false, because eventName:[MTT_CORE_DNS_RESOLVE_INFO] is not allowed in server strategy!

我debug观察到64位手机会回调预加载的方法onViewInitFinished(true), onCoreInitFinished(). 这里面不需要写任何东西吧。32位手机没有回调，也没有这个报错。

感觉问题是DNS解析的原因，求解！

谢谢

**Comment by Im-Kevin** [comment]
你好,我用64位手机试过了,没有出现你说的那个问题,或许是我更新了版本,所以BUG没了,你可以试试更新我这个版本试试,这个版本不需要配置什么,直接添加就行了
