### ISSUE TITLE
不兼容Cordova8.0？

### ISSUE THREAD

**Issue by Frank-C-Zhang** [Im-Kevin/cordova.plugins.X5WebView#3]
我用的Cordova8.0, 发现只要是X5的plugin都安装不上。提示res\xml\config.xml找不到。stockoverflow上说需要降级Corodva到6.X版本。你可以顺便把路径的问题解决一哈吗。如果解决不了我还是用crosswalk来提升性能了。
https://stackoverflow.com/questions/48239010/cordova-does-not-build-res-folder-does-not-exist-under-platform-android

**Comment by Im-Kevin** [comment]
建议你用https://github.com/runner525/x5webview-cordova-plugin 这个是腾讯官方出的,这个项目暂时不继续维护了
